baseURL: "/"
languageCode: "en-us"
title: "All The Best Ways"
paginate: 10

params:
  defaultTheme: auto
  description: "All The Best Ways LLC â€“ tools, stories, and software."
  author: "Joseph Edward Florkevicz"

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: blog
      name: Blog
      url: /posts/
      weight: 2

outputs:
  home:
    - HTML
    - RSS
