baseURL: "https://www.allthebestways.com/"
title: "All The Best Ways"
languageCode: "en-us"
paginate: 10

module:
  imports:
    - path: github.com/adityatelange/hugo-PaperMod

params:
  env: production
  title: "All The Best Ways"
  description: "All The Best Ways LLC"
  author: "All The Best Ways LLC"
  defaultTheme: auto
  disableThemeToggle: false
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 1
    - identifier: posts
      name: Posts
      url: /posts/
      weight: 2

markup:
  goldmark:
    renderer:
      unsafe: true

permalinks:
  posts: "/posts/:slug/"
